Repository FossifyOrg/Contacts, pull requests merged in 2025-05, with the labels that each got.

#263 docs: remove local pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#269 ci: use fossifybot github app token
  .github/workflows/foss-release.yml
  .github/workflows/gplay-release.yml
  .github/workflows/image-minimizer.yml
  .github/workflows/no-response.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/release-commenter.yml
Labels: ci

#273 ci(dependabot): add jitpack registry for gradle
  .github/dependabot.yml
Labels: ci

#277 chore(l10n): update translations
  app/src/main/res/values-pl/strings.xml
Labels: l10n
